package database;

import biblis.Record;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RecordDAO {

    // All records
    public static List<Record> all() {
        ResultSet results;
        List<Record> records = new ArrayList<>();
        try {
            results = Database.query("SELECT * FROM records");
            while (results.next()) {
                int id = results.getInt("id");
                String title = results.getString("title");
                Date date = results.getDate("created");
                String author = results.getString("author");
                String editor = results.getString("editor");
                String pitch = results.getString("pitch");
                records.add(new Record(id, title, date, author, editor, pitch));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            Database.close();
        }
        return records;
    }

    // Find record by id
    public static Record findById(int id) {
        Record record = null;
        ResultSet result;
        try {
            result = Database.query("SELECT * FROM records WHERE id=" + id);
            while (result.next()) {
                int recordId = result.getInt("id");
                String recordTitle = result.getString("title");
                Date recordDate = result.getDate("created");
                String recordAuthor = result.getString("author");
                String recordEditor = result.getString("editor");
                String recordPitch = result.getString("pitch");
                record = new Record(recordId, recordTitle, recordDate, recordAuthor, recordEditor, recordPitch);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }  finally {
            Database.close();
        }
        return record;
    }

    public static void save(Record record) {
        try {
            PreparedStatement preparedStatement = Database.prepared("INSERT INTO records (title, created, author, editor, pitch) VALUES (?, NOW(), ?, ?, ?)",
                    true,
                    record.getRecordTitle(),
                    record.getAuthor(),
                    record.getEditor(),
                    record.getPitch());
            int statut = preparedStatement.executeUpdate();
            if (statut == 0) {
                throw new SQLException("La requête d'insertion à échoué");
            }
            ResultSet autoGeneratedKeys = preparedStatement.getGeneratedKeys();
            if (autoGeneratedKeys.next()) {
                record.setRecordID(autoGeneratedKeys.getInt(1));
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            Database.close();
        }
    }

    public static void update(Record record) {
        try {
            PreparedStatement preparedStatement = Database.prepared("UPDATE records SET title=?, created=NOW(), author=?, editor=?, pitch=? WHERE id=?",
                    false,
                    record.getRecordTitle(),
                    record.getAuthor(),
                    record.getEditor(),
                    record.getPitch(),
                    record.getRecordID());
            int statut = preparedStatement.executeUpdate();
            if (statut == 0) {
                throw new SQLException("La requête de mise à jour à échoué");
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            Database.close();
        }
    }
}
